### ISSUE TITLE
Add binding for setTimeout

### ISSUE THREAD

**Issue by johtso** [gleam-lang/javascript#10]
https://github.com/CrowdHailer/plinth/blob/fd2ef9ef058281a5a6e272fbbae6a7e904c04a83/src/plinth/javascript/global.gleam#L14-L14

**Comment by johtso** [comment]
Oh, is this actually outside of the scope of this package because it's more of a runtime API than a core language feature?

**Comment by lpil** [comment]
Perhaps it's enough that it is in Plinth?
