### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by m4rocks** [gleam-lang/javascript#15]
Hello! First of all, great stuff, very cool language. And now, the gleam_javascript module is pretty nice but it doesn't have a licence. This might involve some legal troubles for people choosing to use this module.

Also I noticed some other Gleam modules also use gleam_javascript which, again, might present some troubles for some businesses or individuals.

I am kindly asking for a licence to be added.

**Comment by lpil** [comment]
Hello! This library is Apache 2 licenced, as specified in the configuration. Do feel free to PR a licence file of you would like. Thank you
