### ISSUE TITLE
`array.to_list` is buggy

### ISSUE THREAD

**Issue by ghivert** [gleam-lang/javascript#17]
Hi!

If you have a `Array(Array(a))`, and have a code like `let content = array.map(content, array.to_list) |> array.to_list`, the generated code is: 
```js                
let content$1 = (() => {
  let _pipe = $array.map(content, $array.to_list);
  return $array.to_list(_pipe);
})();
```
wrong, because here, `$array.to_list` is an alias to `gleam.toList`, which _accepts_ a second argument. The real code is then

```js                
let content$1 = (() => {
  let _pipe = $array.map(content, (item, index) => $array.to_list(item, index));
  return $array.to_list(_pipe);
})();
```

Which breaks the code after this, because it should be compiled as 

```js                
let content$1 = (() => {
  let _pipe = $array.map(content, item => $array.to_list(item));
  return $array.to_list(_pipe);
})();
```

To make sure the second argument of `toList` is empty. 🙂

**Comment by lpil** [comment]
Thank you!
